/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.akkademy;

import org.junit.Test;

import java.util.concurrent.CompletableFuture;

import static org.assertj.core.api.Assertions.assertThat;


public class JavaClientTest {

    @Test
    public void itShouldSetRecord() throws Exception {
        JavaClient client = new JavaClient();
        client.set("123", 123);
    }

}
