/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iot.system;

import akka.actor.ActorRef;
import akka.actor.ActorSystem;
import iot.system.actors.IotSupervisor;

import java.io.IOException;

/**
 * IotMain
 * @author ging wu
 * @date 2018/12/11
 */
public class IotMain {

    public static void main(String[] args) throws IOException {
        ActorSystem system = ActorSystem.create("iot-system");

        try {
            ActorRef supervisor = system.actorOf(IotSupervisor.props(), "iot-supervisor");

            System.out.println("Press ENTER to exit the system");
            System.in.read();
        } finally {
            system.terminate();
        }
    }
}
