/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.0/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenLocal()
    mavenCentral()
    jcenter()
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("com.typesafe.akka:akka-actor_2.12:2.5.18")
    implementation("com.typesafe.akka:akka-remote_2.12:2.5.18")
    implementation("com.google.guava:guava:27.0.1-jre")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
    testImplementation("com.typesafe.akka:akka-testkit_2.12:2.5.18")
    testImplementation("org.assertj:assertj-core:3.8.0")
}

application {
    // Define the main class for the application
    mainClassName = "com.akkademy.App"
}
