/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.akkademy;

import akka.actor.ActorRef;
import akka.actor.ActorSelection;
import akka.actor.ActorSystem;
import com.akkademy.messages.GetRequest;
import com.akkademy.messages.SetRequest;

/**
 * JavaClient
 * @author ging wu
 * @date 2018/12/7
 */
public class JavaClient {

    private final ActorSelection remoteDb;

    public JavaClient() {
        ActorSystem system = ActorSystem.create("LocalSystem");
        remoteDb = system.actorSelection("akka.tcp://akkademy@127.0.0.1:2552/user/akkademy-db");
    }

    public void get(String key) {
        remoteDb.tell(new GetRequest(key), ActorRef.noSender());
    }

    public void set(String key, Object value) {
        remoteDb.tell(new SetRequest(key, value), ActorRef.noSender());
    }

}
